# Setup
title:               Christopher Zou
tagline:             student at UC Berkeley
description:         a site for blogging, teaching, a portfolio, and thoughts given structure
url:                 
baseurl:             /blog
paginate:            5
permalink:           pretty
paginate_path:       /posts/page:num/

# About/contact
author:
  name:              Christopher Zou
  url:               https://github.com/chriswzou
  email:             cwzou@berkeley.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

# Google Analytics
google_analytics: UA-117878188-2
