# Setup
title:               Christopher Zou's Blog
tagline:             student at UC Berkeley
description:         a site for blogging, teaching, my portfolio, and messing around
url:
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Christopher Zou
  url:               https://github.com/chriswzou
  email:             cwzou@berkeley.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
